version: '3.9'

services:
  rails:
    build:
      context: .
      dockerfile: containers/rails/Dockerfile
    command: containers/rails/entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - rails_yarn_cache:/app/node_modules
    ports:
      - "3000:3000"

  vite:
    build:
      context: ./frontend
      dockerfile: ../containers/vite/Dockerfile
    volumes:
      - ./frontend:/app
      - vite_yarn_cache:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  bundle_cache:
  rails_yarn_cache:
  vite_yarn_cache:
